site_name: 'C-LAEF 1k Docs'
site_description: 'Documentation and logs for C-LAEF 1k suite.'
repo_url: 'https://github.com/C-LAEF/claef_1k_doc.git'
repo_name: 'GitHub'
docs_dir: 'docs/'
site_dir: '_site_mkdocs/'
theme: 'readthedocs'
prev_next_buttons_location: 'both'
copyright: 'Carlos Pereira Atencio'
